sudo: required
language: node_js
node_js:
  - "node"

before_install:
 - |
   if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|^(LICENSE)'
   then
     echo "Not running CI since only docs were changed."
     exit
   fi

script:
  - wget -q https://github.com/yshalsager/telegram.py/raw/master/telegram.py
  - chmod +x sync.sh
  - ./sync.sh
