name: cronjob
env:
    GIT_OAUTH_TOKEN_XFU: ${{ secrets.GIT_OAUTH_TOKEN_XFU }}
    BOTTOKEN: ${{ secrets.BOTTOKEN }}

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - name: Run
      run: uv run sync.py
